name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to match your project’s Python version

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libta-lib0 libta-lib-dev
          python -m pip install --upgrade pip
          pip install ta-lib
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run Tests
        run: pytest tests/ --maxfail=5 --disable-warnings --cov=financial_analysis
