name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to match your project’s Python version

      - name: Install TA-Lib Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc
          sudo apt-get install -y libta-lib0 ta-lib

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir ta-lib  # Install TA-Lib wrapper
          pip install -r requirements.txt  # Install other dependencies

      - name: Run Tests
        run: pytest tests/ --maxfail=5 --disable-warnings --cov=financial_analysis
